[package]
name = "baudot"
version = "0.1.1"
authors = ["Matt McPherrin <matt@mcpherrin.ca>"]
repository = "https://github.com/mcpherrinm/baudot.git"
keywords = ["TTY", "TDD", "baudot", "ITA2", "characters"]
license = "MIT"
description = "Baudot and related five bit codes in Rust"
